#!/usr/bin/env python3
"""Read public GitHub growth counters, with optional owner-only traffic data."""
import argparse
from datetime import datetime, timedelta, timezone
import json
import os
from pathlib import Path
import re
import sys
from urllib.error import HTTPError, URLError
from urllib.parse import urlencode
from urllib.request import Request, urlopen

API = "https://api.github.com"
DOWNLOAD_SUFFIXES = (".zip", ".dmg", ".pkg", ".tar.gz", ".tgz", ".tar.xz")


def request_json(path, token=None):
    headers = {"Accept": "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28", "User-Agent": "vinny-growth-snapshot"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    with urlopen(Request(API + path, headers=headers), timeout=30) as response:
        return json.load(response)


def pages(path, token=None):
    separator = "&" if "?" in path else "?"
    page = 1
    while True:
        batch = request_json(f"{path}{separator}per_page=100&page={page}", token)
        yield from batch
        if len(batch) < 100:
            break
        page += 1


def build_snapshot(repo, metadata, releases, issues, now, previous=None):
    if previous and previous.get("repository") != repo:
        raise ValueError("Previous snapshot belongs to a different repository")
    old_assets = {a["id"]: a for a in (previous or {}).get("assets", [])}
    assets = []
    for release in releases:
        if release.get("draft"):
            continue
        for asset in release.get("assets", []):
            if not asset["name"].lower().endswith(DOWNLOAD_SUFFIXES):
                continue
            old = old_assets.get(asset["id"])
            delta = asset["download_count"] - old["downloads"] if old else None
            assets.append({"id": asset["id"], "release": release["tag_name"], "prerelease": release.get("prerelease", False), "name": asset["name"], "url": asset["browser_download_url"], "created_at": asset["created_at"], "downloads": asset["download_count"], "downloads_change": delta if delta is not None and delta >= 0 else None})
    counters = {"stars": metadata["stargazers_count"], "forks": metadata["forks_count"], "open_issues_and_pull_requests": metadata["open_issues_count"]}
    prior_counters = (previous or {}).get("counters", {})
    cutoff = now - timedelta(days=7)
    new_issues = [{"number": i["number"], "title": i["title"], "url": i["html_url"], "created_at": i["created_at"], "state": i["state"]} for i in issues if "pull_request" not in i and datetime.fromisoformat(i["created_at"].replace("Z", "+00:00")) >= cutoff]
    return {"schema_version": 1, "repository": repo, "captured_at": now.isoformat(), "previous_captured_at": (previous or {}).get("captured_at"), "counters": counters, "counter_changes": {key: value - prior_counters[key] if key in prior_counters else None for key, value in counters.items()}, "assets": sorted(assets, key=lambda a: a["id"]), "archive_downloads_total": sum(a["downloads"] for a in assets), "missing_previous_asset_ids": sorted(set(old_assets) - {a["id"] for a in assets}), "issues_created_since": cutoff.isoformat(), "new_issues": sorted(new_issues, key=lambda i: i["created_at"]), "limitations": ["Stars and forks are net counter changes, not unique new people.", "Archive downloads include repeat downloads, bots, and prereleases. They do not measure installations, connections, or retained users.", "Only zip, dmg, pkg, tar.gz, tgz, and tar.xz assets count. Checksums and source archives generated by GitHub are excluded.", "Download changes are null for assets without a prior observation or whose count decreased. Removed assets are reported separately.", "New issues cover the last seven days by creation time, exclude pull requests, and can include closed issues.", "Traffic, when available, covers GitHub's rolling window. Do not sum daily unique counts or overlapping windows."]}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", default="sarimabbas/vinny")
    parser.add_argument("--previous", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--traffic", action="store_true", help="Attempt owner-only visitor and clone data using GH_TOKEN or GITHUB_TOKEN")
    args = parser.parse_args()
    if not re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", args.repo):
        parser.error("--repo must be owner/repository")
    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
    try:
        previous = json.loads(args.previous.read_text()) if args.previous else None
        now = datetime.now(timezone.utc)
        if previous and datetime.fromisoformat(previous["captured_at"].replace("Z", "+00:00")) >= now:
            raise ValueError("Previous snapshot must predate this run")
        base = f"/repos/{args.repo}"
        metadata = request_json(base, token)
        releases = list(pages(base + "/releases", token))
        query = urlencode({"state": "all", "since": (now - timedelta(days=7)).isoformat(), "sort": "created", "direction": "desc"})
        issues = list(pages(base + "/issues?" + query, token))
        snapshot = build_snapshot(args.repo, metadata, releases, issues, now, previous)
        if args.traffic:
            snapshot["traffic"] = {}
            for kind in ("views", "clones"):
                if not token:
                    snapshot["traffic"][kind] = {"unavailable": "GH_TOKEN or GITHUB_TOKEN is required"}
                    continue
                try:
                    snapshot["traffic"][kind] = request_json(base + f"/traffic/{kind}", token)
                except (HTTPError, URLError) as error:
                    snapshot["traffic"][kind] = {"unavailable": f"{type(error).__name__}: {getattr(error, 'code', 'network error')}"}
        args.output.parent.mkdir(parents=True, exist_ok=True)
        temporary = args.output.with_name(args.output.name + ".tmp")
        temporary.write_text(json.dumps(snapshot, indent=2) + "\n")
        temporary.replace(args.output)
        print(f"Saved {args.output}: {snapshot['counters']['stars']} stars, {snapshot['archive_downloads_total']} archive downloads, {len(snapshot['new_issues'])} issues created in the past seven days")
    except (OSError, ValueError, KeyError, TypeError) as error:
        print(f"Snapshot failed: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
